spring:
  application:
    name: clothing-store-backend
  config:
    import:
      - optional:classpath:application-secret.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/clothing_store?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: taido231105
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # update: tự động tạo/cập nhật bảng khớp entity nếu chưa có
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

# ===================== JWT =====================
jwt:
  secret: "QF/hXdGbeSViDt3Zkmem2iandRdI8MzqGqw2V9xMx2g="
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

# ===================== CLOUDINARY =====================
cloudinary:
  cloud-name: "${CLOUDINARY_CLOUD_NAME:duc6hmjgx}"
  api-key: "${CLOUDINARY_API_KEY:152112139729355}"
  api-secret: "${CLOUDINARY_API_SECRET:WAxEHN67BBJ_T_uhkYvz2Oh2gxE}"
  folder: "${CLOUDINARY_FOLDER:FashionShop2}"

# ===================== CORS =====================
cors:
  allowed-origins: "http://localhost:5173"

server:
  port: 8080
